### ISSUE TITLE
too many errors in test

### ISSUE THREAD

**Issue by qursad** [kentsommer/tensorflow-posenet#1]
Hi Kent,
I dont know if youre still using this code,
But it doesnt work with tf1.1.0
Too many errors shows up
Can you take a look at it.
tHx

**Comment by kentsommer** [comment]
Hi @qursad 

Sorry for the late response, in a few weeks I should have time to get this upgraded so that it is compatible with TF1

**Comment by ferchonavarro** [comment]
Hi Kent,

It seems like the code does not work with new version of tensorflow any idea on what is causing the problem so that I can also tried to solve it?

Thanks in advance

**Comment by kentsommer** [comment]
@qursad @ferchonavarro,

I've updated this to be compatible with TF1+

Let me know if you have any more issues, thanks for your patience!
