### ISSUE TITLE
what's the meaning of “-9.123465 -13.208417 1.722406 0.683091 0.543983 -0.314596 0.372154”?

### ISSUE THREAD

**Issue by zg9uagfv** [kentsommer/tensorflow-posenet#11]
in dataset_test.txt, 
`seq8/frame00064.png -9.123465 -13.208417 1.722406 0.683091 0.543983 -0.314596 0.372154`

what's the meaning of “-9.123465 -13.208417 1.722406 0.683091 0.543983 -0.314596 0.372154”?

**Comment by Ramios95** [comment]
same problem

**Comment by FangGet** [comment]
x y z w p q r, means translation vector(3) and rotation vector(in quaternion format)

**Comment by kentsommer** [comment]
Hi, it is the 6dof position + orientation. 3D position + the four components of the quaternion.
