### ISSUE TITLE
Requirements and libraries request

### ISSUE THREAD

**Issue by arturpol94** [kentsommer/tensorflow-posenet#12]
Hi Kent,

I am having issues with running this implementation of posenet.
Could you please provide me with all the requirements and versions of libraries that you were using?

Cheers
Artur

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github.

Most of the versions that were used when this was published are no longer available/supported. If there is a desire to upgrade the code to support newer versions and include a requirements.txt I will happily merge in any pull requests.
