### ISSUE TITLE
train a model in my own datasets

### ISSUE THREAD

**Issue by 18pxrsun** [kentsommer/tensorflow-posenet#14]
Thanks for your code.I met a question when I want to train the model in my own data.The data has six pictures from different directions in each position.Could you give me some suggestions about how to input the data?Thank you very much.

**Comment by kentsommer** [comment]
Closing this out after along hiatus from Github.

Hopefully you managed to get what you need but if not feel free to open a new issue. I believe you probably meant six pictures per position. This should be fine. In general if you can follow the [King's College dataset](https://www.repository.cam.ac.uk/handle/1810/251342) format you should have no problem training on that data. The main key is matching the label format which requires a 6-DOF camera pose.
