### ISSUE TITLE
can not download the starting weights(posenet.npy) from the link

### ISSUE THREAD

**Issue by FQHyuntian** [kentsommer/tensorflow-posenet#15]
Thanks for your code. I am so sorry to bother you because the weight file shared by Google Disk cannot be downloaded. If you can update the link or provide a new download method, I will be very grateful.

**Comment by Phuoc-Hoan-Le** [comment]
Also same, I would be grateful if you can either provide me the starting weight file (posenet.npy) or the trained weight file (PoseNet.ckpt)

**Comment by FQHyuntian** [comment]
You can download the file(posenet.npy) from the link(https://pan.baidu.com/s/1QCzalGbJfCQ4Rrtvu2KNEQ). And the extraction code is (d2e8).

**Comment by CharlesLeeeee** [comment]
Sorry, can you please send it to me in another link because I cannot read in Chinese.

**Comment by Phuoc-Hoan-Le** [comment]
Can you directly send it to me, please? I cannot download it off of Baidu. Thanks!

**Comment by FQHyuntian** [comment]
OK. Please leave your email address, I will send it to you later

**Comment by Phuoc-Hoan-Le** [comment]
le.charles55@gmail.com

**Comment by djaym7** [comment]
Can you send that to jmd.desai08@gmail.com ?

**Comment by marina-neseem** [comment]
Can anyone send it to me as well marinahesham21@gmail.com ?

**Comment by mohanasaik** [comment]
zztlfdo@gmail.com
Please and Thank you!

**Comment by whc233** [comment]
> 感谢您的代码。很抱歉打扰您，因为无法下载 Google Disk 共享的权重文件。如果您能更新链接或提供新的下载方法，我将不胜感激。

您好PoseNet.ckpt有吗可以发一下吗，百度云链接或者qq邮箱297858561@qq.com,不胜感激

**Comment by kentsommer** [comment]
Closing this out after along hiatus from Github.

The README has been updated with a link to the weights which are now hosted with this repository.
