### ISSUE TITLE
cannot load posenet.npy

### ISSUE THREAD

**Issue by JiahaoXia** [kentsommer/tensorflow-posenet#17]
Error information:
UnicodeError: Unpickling a python object failed: UnicodeDecodeError ('ascii', b'C\xc9\x00=\xf6\xbcd\xbd\x08\xe2\x10\xbd\xb4A\x9b\xbc. ...)
You may need to pass the encoding= option to numpy.load
Anyone has this problem?

**Comment by kentsommer** [comment]
Closing this out after along hiatus from Github.

The README has been updated with a link to the weights which are now hosted with this repository.
