### ISSUE TITLE
No starting and trained weights file found on the link.

### ISSUE THREAD

**Issue by kunalchoudhary33** [kentsommer/tensorflow-posenet#18]
Hey,
I appreciate your work. I was planning to train the network with the dataset but was unable to find the posenet.npy and PoseNet.ckpt respectively on the given link. Can you plaese share the files. It would be a greate favour to me.
Regards,
Kunal

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github.

Sadly the trained weights have been lost, however, I did manage to recover the starting weights and have updated the readme so that those are available again.
