### ISSUE TITLE
PoseNet.ckpt weights

### ISSUE THREAD

**Issue by gunshi** [kentsommer/tensorflow-posenet#2]
Hey, 
just wanted a clarification of what stage the weights in file PoseNet.ckpt are from?
They're after training on cambridge landmarks dataset(initialised from model trained on places dataset) while posenet.npy has weights only trained on places dataset?

Thanks for the implementation!
Gunshi

**Comment by kentsommer** [comment]
@gunshi 

The posenet.npy file is taken from here: http://3dvision.princeton.edu/pvt/GoogLeNet/

You are correct, posenet.npy contains the weights for Inception (what posenet is based off of) trained on the places dataset. 

PoseNet.ckpt contains the finals weights after fine-tuning given posenet.npy as the starting weights.

**Comment by milanhenkrich** [comment]
Hey,
Great implementation!

However, the link for posenet.npy is not working anymore. Do you know where else I can get posenet.npy? 
Thank you

**Comment by hyperchris** [comment]
You can get the ckpt and npy from [this link](https://drive.google.com/file/d/0B5DVPd_zGgc8ZmJ0VmNiTXBGUkU/view). I got the link from the [pytorch implementation](https://github.com/ElephantGit/pytorch-posenet).
