### ISSUE TITLE
Not learning learning - ShopFacade dataset

### ISSUE THREAD

**Issue by milanhenkrich** [kentsommer/tensorflow-posenet#3]
Hey there! 
Great implementation, thank you very much. 

I just have one problem, I tried to train it on the project ShopFacade from http://mi.eng.cam.ac.uk/projects/relocalisation/ ... (should work same as King's College).
But my loss variates a lot (it increases and decreases) and after 30 000 iterations, its value is about 15. Are there any parameters that I need to change? 

Can you help me? I am quite new in this field. 
Thank you very much!

**Comment by kentsommer** [comment]
Hi @milanhenkrich 

As shown in the original paper, PoseNet does not perform well on the ShopFacade dataset. That is not specific to this implementation.
