### ISSUE TITLE
Network Initial Error

### ISSUE THREAD

**Issue by hxqiu** [kentsommer/tensorflow-posenet#5]
Hi Kent,
I am studying on the original paper and your code on win10, Python 3.6, tf 1.3.0 recently.
Few days ago i run your code and everything goes well (I made some little changes to make sure it work on new version of tf and Python).But after updated tensorflow I found the problem as below. I took a day to solve it but it still doesn't work.

> Reloaded modules: network, posenet
> 100%|██████████| 343/343 [00:13<00:00, 24.73it/s]
> 100%|██████████| 343/343 [00:00<00:00, 4616.51it/s]
> 100%|██████████| 343/343 [00:00<00:00, 1799.25it/s]
> Traceback (most recent call last):
> 
>   File "<ipython-input-40-b34218f041b7>", line 1, in <module>
>     runfile('D:/tensorflow-posenet-master/test.py', wdir='D:/tensorflow-posenet-master')
> 
>   File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "D:/tensorflow-posenet-master/test.py", line 167, in <module>
>     main()
> 
>   File "D:/tensorflow-posenet-master/test.py", line 124, in main
>     net = PoseNet({'data': image})
> 
>   File "D:\tensorflow-posenet-master\network.py", line 62, in __init__
>     self.setup()
> 
>   File "D:\tensorflow-posenet-master\posenet.py", line 6, in setup
>     .conv(7, 7, 64, 2, 2, name='conv1')
> 
>   File "D:\tensorflow-posenet-master\network.py", line 36, in layer_decorated
>     layer_output = op(self, layer_input, *args, **kwargs)
> 
>   File "D:\tensorflow-posenet-master\network.py", line 142, in conv
>     kernel = self.make_var('weights', shape=[k_h, k_w, int(c_i) / group, c_o]) #change for python 3.6 by Hx
> 
>   File "D:\tensorflow-posenet-master\network.py", line 113, in make_var
>     return tf.get_variable(name, shape, trainable=self.trainable)
> 
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1065, in get_variable
>     use_resource=use_resource, custom_getter=custom_getter)
> 
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 962, in get_variable
>     use_resource=use_resource, custom_getter=custom_getter)
> 
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 367, in get_variable
>     validate_shape=validate_shape, use_resource=use_resource)
> 
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 352, in _true_getter
>     use_resource=use_resource)
> 
>   File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 682, in _get_single_variable
>     "VarScope?" % name)
> 
> ValueError: Variable conv1/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I found problem is caused at the time of the initiation of the network on the line below, can you take a look at what the problem is?
Or could you tell me your environment so I can run it?
https://github.com/kentsommer/tensorflow-posenet/blob/7c651379fa91fd39e286027475e1232c9d9baaa0/test.py#L122

Thanks!

**Comment by muma1018** [comment]
I encounter a similar issue.
I can run the network once, but re-running throws this error.

_ValueError: Variable conv1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:_

Running in Terminal works fine though.

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github. There have been a lot of updates across many of the utilized frameworks since this was published. Unfortunately I do not have the time to update it which is most likely why these issues cropped/are cropping up.

I will happily merge in any pull requests if folks have a desire to keep this working.
