### ISSUE TITLE
Some Errors in Subtracte mean when test and train

### ISSUE THREAD

**Issue by HyuanTan** [kentsommer/tensorflow-posenet#6]
@kentsommer Hi, Thanks for share!
In the `test.py` and `train.py`:
`
X = cv2.imread(images[i]) # Read image using cv2, get BGR image

mean = np.zeros((1, 3, 224, 224))
for X in tqdm(images_cropped):

mean[0][0] += X[:,:,0] # Get BGR means
mean[0][1] += X[:,:,1]
mean[0][2] += X[:,:,2]
N += 1
mean[0] /= N

for X in tqdm(images_cropped):
  X = np.transpose(X,(2,0,1))＃Transform image from BGR to RGB
  X = X - mean　#But using RGB image minus BGR means
  X = np.squeeze(X)
  X = np.transpose(X, (1,2,0))＃Transform RGB image back to BGR image.
  Y = np.expand_dims(X, axis=0)
  images_out.append(Y)
`
Maybe there are some errors when the image minus the means. You used the  RGB image minus BGR means.

**Comment by kentsommer** [comment]
@HyuanTan 

Good catch, I'll patch this shortly.

**Comment by ClaudioCimarelli** [comment]
@HyuanTan @kentsommer 
Even if this has been closed, I would like to note that there are still a couple of problems. 
Firstly, (after the fix) the image should be indexed in a different way: X[0,:,:] X[1,:,:] X[2,:,:].
Secondly, doing the transpose does not change the order of the channels! We should invert the image tensor along the dimension of the channel, ie the first after the transpose operation. 
Hope this is useful for someone else.
