### ISSUE TITLE
Converting Model

### ISSUE THREAD

**Issue by WankaiLiu** [kentsommer/tensorflow-posenet#7]
Thanks for your code.
Regarding “The starting and trained weights (posenet.npy and PoseNet.ckpt respectively) for training were obtained by converting caffemodel weights from here and then training.", how can I convert the model from caffe to tensorflow?

Thanks a lot.

**Comment by kentsommer** [comment]
Hi @WankaiLiu,

Here is the source for the code used to convert: https://github.com/ethereon/caffe-tensorflow
