### ISSUE TITLE
 operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by tongpinmo** [kentsommer/tensorflow-posenet#9]
when i run the test.py ,the problem is listed as below:

 operands could not be broadcast together with shapes    (224,224) (3,224) (224,224) 
 tensorflow version :1.2
I don't  know why ?

**Comment by tongpinmo** [comment]
i have solved it .in the line 57 of test.py ,you don't need to transpose X

**Comment by ticlazau** [comment]
Hello @tongpinmo 
So what did you change on line 57? From "X = np.transpose(X,(2,0,1))" to what?

**Comment by tongpinmo** [comment]
> Hello @tongpinmo
> So what did you change on line 57? From "X = np.transpose(X,(2,0,1))" to what?
  for i in tqdm(range(len(images))):
        X = cv2.imread(images[i])
        # print('shape of X: =',X.shape)  #shape(1080,1920,3)
        X = cv2.resize(X, (455, 256))     #shape(256,455,3)
        X = centeredCrop(X, 224)          #shape(224,224,3)
        images_cropped.append(X)
is ok !

**Comment by tongpinmo** [comment]
@ticlazau 
    for i in tqdm(range(len(images))):
        X = cv2.imread(images[i])
        # print('shape of X: =',X.shape)  #shape(1080,1920,3)
        X = cv2.resize(X, (455, 256))     #shape(256,455,3)
        X = centeredCrop(X, 224)          #shape(224,224,3)
        images_cropped.append(X)
is ok !

**Comment by ticlazau** [comment]
I have this section: 

def preprocess(images):
        images_out = [] #final result
        #Resize and crop and compute mean!
        images_cropped = []
        for i in tqdm(range(len(images))):
                X = cv2.imread(images[i])
                X = cv2.resize(X, (455, 256))
                X = centeredCrop(X, 224)
                images_cropped.append(X)
        #compute images mean
        N = 0
        mean = np.zeros((1, 3, 224, 224))
        for X in tqdm(images_cropped):
                X = np.transpose(X,(2,0,1))
                mean[0][0] += X[:,:,0]
                mean[0][1] += X[:,:,1]
                mean[0][2] += X[:,:,2]
                N += 1
        mean[0] /= N
        #Subtract mean from all images
        for X in tqdm(images_cropped):
                X = np.transpose(X,(2,0,1))
                X = X - mean
                X = np.squeeze(X)
                X = np.transpose(X, (1,2,0))
                images_out.append(X)
        return images_out

Is the same as the one you mentioned but same error:

python train.py
100%|██████████████████████████████████████████████████████████████████████████████████████| 1220/1220 [00:51<00:00, 23.59it/s]
  0%|                                                                                                 | 0/1220 [00:00<?, ?it/s]Exception KeyError: KeyError(<weakref at 0x7fff5d262260; to 'tqdm' at 0x7fff5d263350>,) in <bound method tqdm.__del__ of   0%|                                                                                                 | 0/1220 [00:00<?, ?it/s]> ignored
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main()
  File "train.py", line 113, in main
    datasource = get_data()
  File "train.py", line 82, in get_data
    images = preprocess(images)
  File "train.py", line 49, in preprocess
    mean[0][0] += X[:,:,0]
ValueError: operands could not be broadcast together with shapes (224,224) (3,224) (224,224)

:(

**Comment by ticlazau** [comment]
Any ideas?

**Comment by ticlazau** [comment]
@tongpinmo  I have fixed some issues mentioned above, but the initial error to the topic is still there:

Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main()
  File "train.py", line 113, in main
    datasource = get_data()
  File "train.py", line 82, in get_data
    images = preprocess(images)
  File "train.py", line 49, in preprocess
    mean[0][0] += X[:,:,0]
ValueError: operands could not be broadcast together with shapes (224,224) (3,224) (224,224)

**Comment by RobertFlame** [comment]
@ticlazau I think you need to remove line48 in train.py which conducts transpose of X. This line of code is in function preprocess(images) .

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github. There have been a lot of updates across many of the utilized frameworks since this was published. Unfortunately I do not have the time to update it which is most likely why these issues cropped/are cropping up.

I will happily merge in any pull requests if folks have a desire to keep this working.
